version: '3.1'
services:
 redis:
   image: redis
   container_name: my_redis
   restart: always
   command: redis-server --requirepass ILoveFaker
   ports:
     - "6371:6379"
   volumes:
     - ./data:/data